/** Error codes returned by the Maintenance Monitor API (`code` in the error envelope). */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CORS_ORIGIN_DENIED: 'CORS_ORIGIN_DENIED',

  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TEMPORARY_PASSWORD_EXPIRED: 'TEMPORARY_PASSWORD_EXPIRED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  PASSWORD_REUSE: 'PASSWORD_REUSE',

  FORBIDDEN: 'FORBIDDEN',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_PHONE_EXISTS: 'USER_PHONE_EXISTS',
  USER_SELF_MODIFICATION_FORBIDDEN: 'USER_SELF_MODIFICATION_FORBIDDEN',
  USER_NOT_TECHNICIAN: 'USER_NOT_TECHNICIAN',
  USER_INACTIVE: 'USER_INACTIVE',

  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  MACHINE_SERIAL_EXISTS: 'MACHINE_SERIAL_EXISTS',
  MACHINE_INACTIVE: 'MACHINE_INACTIVE',
  MACHINE_HAS_OPEN_LOGS: 'MACHINE_HAS_OPEN_LOGS',

  MACHINE_LOG_NOT_FOUND: 'MACHINE_LOG_NOT_FOUND',
  MACHINE_STATE_CONFLICT: 'MACHINE_STATE_CONFLICT',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  INVALID_LOG_STATUS: 'INVALID_LOG_STATUS',
  INVALID_LOG_TIMES: 'INVALID_LOG_TIMES',
  INVALID_DOWNTIME: 'INVALID_DOWNTIME',
  RESULTING_STATE_IMMUTABLE: 'RESULTING_STATE_IMMUTABLE',
  STALE_VERSION: 'STALE_VERSION',

  INVALID_TIME_RANGE: 'INVALID_TIME_RANGE',
} as const;

/** Errors produced by the client itself, when no API response is available. */
export const ClientErrorCode = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  CANCELLED: 'CANCELLED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ApiErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
export type AppErrorCode = ApiErrorCode | (typeof ClientErrorCode)[keyof typeof ClientErrorCode];
